version: "3.9"

services:
  registry:
    image: "registry:latest"
    ports:
      - "443:443"
    environment:
      REGISTRY_AUTH: "htpasswd"
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: "/auth/registry.password"
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry_data
    volumes:
      - "base_shared_data:/registry_data"
