# TODO: Use Secrets to store the passwords to all containers.
version: "3.9"

services:
  wireguard:
    image: "weejewel/wg-easy"
    container_name: "wireguard"
    restart: "unless-stopped"
    networks:
      - "public"
      - "local"
    cap_add:
      - "NET_ADMIN"
      - "SYS_MODULE"
    sysctls:
      - "net.ipv4.ip_forward=1"
      - "net.ipv4.conf.all.src_valid_mark=1"
    ports:
      - "${WIREGUARD_PORT?Variable not set}:51820/udp"
      - "${WG_EASY_PORT?Variable not set}:51821/tcp"
    environment:
      - "WG_HOST=${WIREGUARD_HOST?Variable not set}"
      - "WG_PORT=${WIREGUARD_PORT?Variable not set}"
      - "PASSWORD=${WG_EASY_PASSWORD?Variable not set}"
    volumes:
      - "wg_easy_data:/etc/wireguard"
    security_opt:
      - "no-new-privileges:true"

volumes:
  wg_easy_data:
    name: "wg_easy_data"

networks:

  # ! Public network should be created before composing.
  public:
    # Set as name the public network, you wish your stack to communicate with.
    # External means it would be accesible from outside the stack too.
    name: "public"
    external: true
  local:
    # Set as name the local network, you wish your stack to communicate with.
    name: "local"
    external: true
